item {
  id: 1
  name: 'Traffic sign 1'
}

item {
  id: 2
  name: 'Traffic sign 2'
}

item {
  id: 3
  name: 'Traffic sign 3'
}

item {
  id: 4
  name: 'Traffic sign 4'
}

item {
  id: 5
  name: 'Traffic sign 5'
}

item {
  id: 6
  name: 'Traffic sign 6'
}

item {
  id: 7
  name: 'Traffic sign 7'
}

item {
  id: 8
  name: 'Traffic sign 8'
}

item {
  id: 9
  name: 'Traffic sign 9'
}

item {
  id: 10
  name: 'Traffic sign 10'
}

item {
  id: 11
  name: 'Traffic sign 11'
}

item {
  id: 12
  name: 'Traffic sign 12'
}

item {
  id: 13
  name: 'Traffic sign 13'
}

item {
  id: 14
  name: 'Traffic sign 14'
}

item {
  id: 15
  name: 'Traffic sign 15'
}

item {
  id: 16
  name: 'Traffic sign 16'
}

item {
  id: 17
  name: 'Traffic sign 17'
}

item {
  id: 18
  name: 'Traffic sign 18'
}

item {
  id: 19
  name: 'Traffic sign 19'
}

item {
  id: 20
  name: 'Traffic sign 20'
}

item {
  id: 21
  name: 'Traffic sign 21'
}

item {
  id: 22
  name: 'Traffic sign 22'
}

item {
  id: 23
  name: 'Traffic sign 23'
}

item {
  id: 24
  name: 'Traffic sign 24'
}

item {
  id: 25
  name: 'Traffic sign 25'
}

item {
  id: 26
  name: 'Traffic sign 26'
}

item {
  id: 27
  name: 'Traffic sign 27'
}

item {
  id: 28
  name: 'Traffic sign 28'
}

item {
  id: 29
  name: 'Traffic sign 29'
}

item {
  id: 30
  name: 'Traffic sign 30'
}

item {
  id: 31
  name: 'Traffic sign 31'
}

item {
  id: 32
  name: 'Traffic sign 32'
}

item {
  id: 33
  name: 'Traffic sign 33'
}

item {
  id: 34
  name: 'Traffic sign 34'
}

item {
  id: 35
  name: 'Traffic sign 35'
}

item {
  id: 36
  name: 'Traffic sign 36'
}

item {
  id: 37
  name: 'Traffic sign 37'
}

item {
  id: 38
  name: 'Traffic sign 38'
}

item {
  id: 39
  name: 'Traffic sign 39'
}

item {
  id: 40
  name: 'Traffic sign 40'
}

item {
  id: 41
  name: 'Traffic sign 41'
}

item {
  id: 42
  name: 'Traffic sign 42'
}

item {
  id: 43
  name: 'Traffic sign 43'
}

